language: java
jdk:
  - oraclejdk8
install: true
script:
  - ./gradlew build --exclude-task test
notifications:
  slack: ftsrg:YMFDeJB1YkOli9BXOKvtoB1Y
  email: false
  on_success: change
  on_failure: always
branches:
  except:
  - ingraph
